name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deployments
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Step 2: Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Step 3: Use latest Node.js
      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # Step 4: Setup Python and install dependencies
      - name: Setup Python and Install Deps
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install npm and Python dependencies
        run: |
          npm install
          pip install requests pandas

      # Step 5: Install & Activate EMSDK + Build Everything
      - name: Install Emscripten and Build Project
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
          npm run build
        shell: bash

      # Step 6: Upload `dist` folder for GitHub Pages
      - name: Upload Build Output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          retention-days: 5

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
